hpc <- read.table("household_power_consumption.txt",sep=";",stringsAsFactors = FALSE)
hpc <- subset(hpc,hpc$V1=='1/2/2007' | hpc$V1=='2/2/2007')
colnames(hpc)<- c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3")
hpc$TimeStamp <- paste(hpc$Date,hpc$Time)
png(filename="plot3.png")
plot(strptime(hpc$TimeStamp,"%d/%m/%Y %H:%M:%S"),hpc$Sub_metering_1,type='l',col="black",ylab="Energy sub metering",xlab="")
lines(strptime(hpc$TimeStamp,"%d/%m/%Y %H:%M:%S"),hpc$Sub_metering_2,type='l',col="red")
lines(strptime(hpc$TimeStamp,"%d/%m/%Y %H:%M:%S"),hpc$Sub_metering_3,type='l',col="blue")
legend("topright",lty=1,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),cex=0.75)
dev.off()
